"user client";
import { Geist, Geist_Mono, Poppins } from "next/font/google";

import "./globals.css";
import Navbar from "@/app/(frontend)/_components/_navbar/Navbar";
import Logout from "@/app/(frontend)/_components/_navbar/Logout";
import { Provider } from "@/components/ui/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",

  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",

  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased flex justify-center items-start bg-[radial-gradient(ellipse_1000px_400px_at_50%_-20%,_#588027_1%,_#ffffff_90%)]`}
      >
        <Logout />
        <Provider>{children}</Provider>
        <Navbar />
      </body>
    </html>
  );
}
